import "./globals.css";
import type { Metadata } from "next";
import { headers } from 'next/headers'
import { Inter } from "next/font/google";
import { cookieToInitialState } from 'wagmi'

import { getConfig } from "@/lib/wagmi"
import { Providers } from "@/app/providers";
import TopNav from "@/components/top-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    getConfig(),
    headers().get('cookie'),
  )
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers initialState={initialState}>
          <div className="min-h-screen">
            <TopNav />
            <main className="container mx-auto p-8 max-w-3xl">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
